
CREATE TABLE IF NOT EXISTS `categories` (
  `cat_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cat_title` VARCHAR(255),
  PRIMARY KEY `pk_cat_id`(`cat_id`)
);

insert into `categories`(`cat_title`) values
('example1'),
('example2'),
('example3'),
('example4');




CREATE TABLE IF NOT EXISTS `products` (
  `product_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_title` VARCHAR(255) NOT NULL,
  `product_category_id` INT(11) UNSIGNED NOT NULL,
  `product_price` FLOAT(11) NOT NULL,
  `product_short_desc` VARCHAR(300) NOT NULL,
  `product_description` TEXT NOT NULL,
  `product_image` TEXT NOT NULL,
  PRIMARY KEY `pk_product_id`(`product_id`)
);
-- ALTER TABLE `products` ADD `product_short_desc` VARCHAR(300) NOT NULL AFTER `product_description`; 
-- ALTER TABLE `products` ADD `product_image` VARCHAR(255) NOT NULL AFTER `product_description`; 


-- insert into `products`(`product_title`,`product_category_id`,`product_price`,`product_description`) values
-- ('example1'),
-- ('example2'),
-- ('example3'),
-- ('example4');


UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.sem. Nulla interdum. Curabitur dictum. Phasellus in felis. sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae", product_image = "image.png" WHERE product_id = 1;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.et ultrices posuere cubilia Curae; Phasellus ornare. Fusce et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor", product_image = "image.png" WHERE product_id = 2;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.rutrum urna, nec luctus felis purus ac tellus. Suspendisse rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula", product_image = "image.png" WHERE product_id = 3;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.bibendum fermentum metus. Aenean sed pede nec ante blandit bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare", product_image = "image.png" WHERE product_id = 4;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.dui. Cum sociis natoque penatibus et magnis dis parturient dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget", product_image = "image.png" WHERE product_id = 5;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.ligula. Donec luctus aliquet odio. Etiam ligula tortor, dicligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna.", product_image = "image.png" WHERE product_id = 6;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Dolorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet,", product_image = "image.png" WHERE product_id = 7;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.ligula tortor, dictum eu, placerat eget, venenatis a, magnaligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer", product_image = "image.png" WHERE product_id = 8;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.scelerisque neque. Nullam nisl. Maecenas malesuada fringillscelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit.", product_image = "image.png" WHERE product_id = 9;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pegestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue", product_image = "image.png" WHERE product_id = 10;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.urna. Ut tincidunt vehicula risus. Nulla eget metus eu eraturna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam,", product_image = "image.png" WHERE product_id = 11;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.malesuada vel, venenatis vel, faucibus id, libero. Donec comalesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor,", product_image = "image.png" WHERE product_id = 12;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.laoreet, libero et tristique pellentesque, tellus sem mollilaoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus.", product_image = "image.png" WHERE product_id = 13;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.tristique aliquet. Phasellus fermentum convallis ligula. Dotristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu,", product_image = "image.png" WHERE product_id = 14;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eunon, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed", product_image = "image.png" WHERE product_id = 15;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.molestie orci tincidunt adipiscing. Mauris molestie pharetrmolestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl", product_image = "image.png" WHERE product_id = 16;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper", product_image = "image.png" WHERE product_id = 17;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi", product_image = "image.png" WHERE product_id = 18;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.egestas a, dui. Cras pellentesque. Sed dictum. Proin eget oegestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed", product_image = "image.png" WHERE product_id = 19;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsudui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh", product_image = "image.png" WHERE product_id = 20;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisnisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in", product_image = "image.png" WHERE product_id = 21;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.scelerisque, lorem ipsum sodales purus, in molestie tortor scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis", product_image = "image.png" WHERE product_id = 22;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra,Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum", product_image = "image.png" WHERE product_id = 23;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed", product_image = "image.png" WHERE product_id = 24;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.faucibus orci luctus et ultrices posuere cubilia Curae; Phafaucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet", product_image = "image.png" WHERE product_id = 25;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Alia, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu", product_image = "image.png" WHERE product_id = 26;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.justo sit amet nulla. Donec non justo. Proin non massa non justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis", product_image = "image.png" WHERE product_id = 27;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Nullam suscipit, est ac facilisis facilisis, magna tellus fNullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit", product_image = "image.png" WHERE product_id = 28;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.eget lacus. Mauris non dui nec urna suscipit nonummy. Fusceeget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante", product_image = "image.png" WHERE product_id = 29;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.magna. Phasellus dolor elit, pellentesque a, facilisis non,magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis", product_image = "image.png" WHERE product_id = 30;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat", product_image = "image.png" WHERE product_id = 31;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Maecenas ornare egestas ligula. Nullam feugiat placerat velMaecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam", product_image = "image.png" WHERE product_id = 32;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisnec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin", product_image = "image.png" WHERE product_id = 33;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.ultricies sem magna nec quam. Curabitur vel lectus. Cum socultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis", product_image = "image.png" WHERE product_id = 34;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Nam ac nulla. In tincidunt congue turpis. In condimentum. DNam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum", product_image = "image.png" WHERE product_id = 35;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.elementum, lorem ut aliquam iaculis, lacus pede sagittis auelementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam.", product_image = "image.png" WHERE product_id = 36;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Vivamus sit amet risus. Donec egestas. Aliquam nec enim. NuVivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est,", product_image = "image.png" WHERE product_id = 37;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.vitae aliquam eros turpis non enim. Mauris quis turpis vitavitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida.", product_image = "image.png" WHERE product_id = 38;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique", product_image = "image.png" WHERE product_id = 39;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.bibendum ullamcorper. Duis cursus, diam at pretium aliquet,bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui", product_image = "image.png" WHERE product_id = 40;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.diam luctus lobortis. Class aptent taciti sociosqu ad litordiam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos", product_image = "image.png" WHERE product_id = 41;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.est. Nunc laoreet lectus quis massa. Mauris vestibulum, neqest. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius", product_image = "image.png" WHERE product_id = 42;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus", product_image = "image.png" WHERE product_id = 43;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.ultrices a, auctor non, feugiat nec, diam. Duis mi enim, coultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis", product_image = "image.png" WHERE product_id = 44;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.orci luctus et ultrices posuere cubilia Curae; Phasellus ororci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam", product_image = "image.png" WHERE product_id = 45;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.nunc. In at pede. Cras vulputate velit eu sem. Pellentesquenunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend", product_image = "image.png" WHERE product_id = 46;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Cras sed leo. Cras vehicula aliquet libero. Integer in magnCras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a,", product_image = "image.png" WHERE product_id = 47;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Nam porttitor scelerisque neque. Nullam nisl. Maecenas maleNam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet.", product_image = "image.png" WHERE product_id = 48;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.luctus. Curabitur egestas nunc sed libero. Proin sed turpisluctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget", product_image = "image.png" WHERE product_id = 49;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Aliquam vulputate ullamcorper magna. Sed eu eros. Nam conseAliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec", product_image = "image.png" WHERE product_id = 50;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.diam. Proin dolor. Nulla semper tellus id nunc interdum feudiam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem", product_image = "image.png" WHERE product_id = 51;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue", product_image = "image.png" WHERE product_id = 52;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.consectetuer adipiscing elit. Curabitur sed tortor. Integerconsectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu", product_image = "image.png" WHERE product_id = 53;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.pellentesque eget, dictum placerat, augue. Sed molestie. Sepellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class", product_image = "image.png" WHERE product_id = 54;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Suspendisse ac metus vitae velit egestas lacinia. Sed conguSuspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla", product_image = "image.png" WHERE product_id = 55;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.eu dui. Cum sociis natoque penatibus et magnis dis parturieeu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean", product_image = "image.png" WHERE product_id = 56;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,", product_image = "image.png" WHERE product_id = 57;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.id, blandit at, nisi. Cum sociis natoque penatibus et magniid, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus", product_image = "image.png" WHERE product_id = 58;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.non, feugiat nec, diam. Duis mi enim, condimentum eget, volnon, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec", product_image = "image.png" WHERE product_id = 59;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.dictum mi, ac mattis velit justo nec ante. Maecenas mi felidictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate,", product_image = "image.png" WHERE product_id = 60;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.habitant morbi tristique senectus et netus et malesuada famhabitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus", product_image = "image.png" WHERE product_id = 61;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.lorem fringilla ornare placerat, orci lacus vestibulum lorelorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam.", product_image = "image.png" WHERE product_id = 62;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.at, nisi. Cum sociis natoque penatibus et magnis dis parturat, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin", product_image = "image.png" WHERE product_id = 63;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Donec tempus, lorem fringilla ornare placerat, orci lacus vDonec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna", product_image = "image.png" WHERE product_id = 64;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.dis parturient montes, nascetur ridiculus mus. Aenean eget dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam", product_image = "image.png" WHERE product_id = 65;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.amet, dapibus id, blandit at, nisi. Cum sociis natoque penaamet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes,", product_image = "image.png" WHERE product_id = 66;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.velit. Aliquam nisl. Nulla eu neque pellentesque massa lobovelit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc", product_image = "image.png" WHERE product_id = 67;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Mauris ut quam vel sapien imperdiet ornare. In faucibus. MoMauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus.", product_image = "image.png" WHERE product_id = 68;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.faucibus leo, in lobortis tellus justo sit amet nulla. Donefaucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa", product_image = "image.png" WHERE product_id = 69;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eCurae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl", product_image = "image.png" WHERE product_id = 70;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.ullamcorper, nisl arcu iaculis enim, sit amet ornare lectusullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet", product_image = "image.png" WHERE product_id = 71;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.blandit. Nam nulla magna, malesuada vel, convallis in, cursblandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat", product_image = "image.png" WHERE product_id = 72;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a,", product_image = "image.png" WHERE product_id = 73;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.mattis semper, dui lectus rutrum urna, nec luctus felis purmattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor.", product_image = "image.png" WHERE product_id = 74;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.imperdiet, erat nonummy ultricies ornare, elit elit fermentimperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc.", product_image = "image.png" WHERE product_id = 75;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.In at pede. Cras vulputate velit eu sem. Pellentesque ut ipIn at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.", product_image = "image.png" WHERE product_id = 76;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.amet, risus. Donec nibh enim, gravida sit amet, dapibus id,amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis", product_image = "image.png" WHERE product_id = 77;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Quisque fringilla euismod enim. Etiam gravida molestie arcuQuisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.", product_image = "image.png" WHERE product_id = 78;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut miarcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor", product_image = "image.png" WHERE product_id = 79;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.iaculis enim, sit amet ornare lectus justo eu arcu. Morbi siaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor", product_image = "image.png" WHERE product_id = 80;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.lacinia. Sed congue, elit sed consequat auctor, nunc nulla lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat", product_image = "image.png" WHERE product_id = 81;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eunon, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed", product_image = "image.png" WHERE product_id = 82;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.nunc sit amet metus. Aliquam erat volutpat. Nulla facilisisnunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla.", product_image = "image.png" WHERE product_id = 83;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.vel nisl. Quisque fringilla euismod enim. Etiam gravida molvel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris", product_image = "image.png" WHERE product_id = 84;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.iaculis aliquet diam. Sed diam lorem, auctor quis, tristiquiaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi.", product_image = "image.png" WHERE product_id = 85;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Quisque tincidunt pede ac urna. Ut tincidunt vehicula risusQuisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper", product_image = "image.png" WHERE product_id = 86;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.tempor diam dictum sapien. Aenean massa. Integer vitae nibhtempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis", product_image = "image.png" WHERE product_id = 87;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consein, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit", product_image = "image.png" WHERE product_id = 88;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.libero. Morbi accumsan laoreet ipsum. Curabitur consequat, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper", product_image = "image.png" WHERE product_id = 89;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.sem, consequat nec, mollis vitae, posuere at, velit. Cras lsem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget,", product_image = "image.png" WHERE product_id = 90;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.mauris id sapien. Cras dolor dolor, tempus non, lacinia at,mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu", product_image = "image.png" WHERE product_id = 91;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.gravida sit amet, dapibus id, blandit at, nisi. Cum sociis gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis", product_image = "image.png" WHERE product_id = 92;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. NNulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas,", product_image = "image.png" WHERE product_id = 93;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.metus vitae velit egestas lacinia. Sed congue, elit sed conmetus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui,", product_image = "image.png" WHERE product_id = 94;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.turpis. In condimentum. Donec at arcu. Vestibulum ante ipsuturpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et", product_image = "image.png" WHERE product_id = 95;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.dui. Suspendisse ac metus vitae velit egestas lacinia. Sed dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc", product_image = "image.png" WHERE product_id = 96;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.rutrum, justo. Praesent luctus. Curabitur egestas nunc sed rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit", product_image = "image.png" WHERE product_id = 97;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec,", product_image = "image.png" WHERE product_id = 98;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Nulla tincidunt, neque vitae semper egestas, urna justo fauNulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget", product_image = "image.png" WHERE product_id = 99;
UPDATE products SET product_description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero dicta voluptates voluptatem possimus! Necessitatibus nesciunt quam sed id ipsum sint architecto voluptatum vero dolorum debitis possimus, cupiditate praesentium libero! Eaque?
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis animi ullam exercitationem excepturi vel, facere laboriosam incidunt soluta in deleniti tempore atque sit eos officia! Eligendi dignissimos sunt aliquid corrupti.Pellentesque habitant morbi tristique senectus et netus et Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet", product_image = "image.png" WHERE product_id = 100;
 